/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.26
 * Generated at: 2022-11-21 09:13:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>header</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"icon/BookSaTong.svg\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/link.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/header.css\">\r\n");
      out.write("    <script src=\"js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $(\".text\").focusin(function () {\r\n");
      out.write("                $(this).addClass(\"active\")\r\n");
      out.write("            })\r\n");
      out.write("            $(\".text\").focusout(function () {\r\n");
      out.write("                $(this).removeClass(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("\r\n");
      out.write("            // 메뉴 마우스 호버\r\n");
      out.write("            $(\".headBottom\").mouseover(function () {\r\n");
      out.write("                $(\".sub\").stop().slideDown(500);\r\n");
      out.write("                $(\".subBg\").stop().slideDown(500);\r\n");
      out.write("            })\r\n");
      out.write("            $(\".headBottom\").mouseout(function () {\r\n");
      out.write("                $(\".sub\").stop().slideUp(500);\r\n");
      out.write("                $(\".subBg\").stop().slideUp(500);\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // 메뉴 클릭시 색깔 변화\r\n");
      out.write("            $(\".headerMenu>li\").mouseover(function () {\r\n");
      out.write("                $(this).addClass(\"active\").siblings().removeClass(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("            $(\".headerMenu>li\").mouseout(function () {\r\n");
      out.write("                $(this).removeClass(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("            $(\".sub>li\").mouseover(function () {\r\n");
      out.write("                $(this).addClass(\"active\").siblings().removeClass(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("            $(\".sub>li\").mouseout(function () {\r\n");
      out.write("                $(this).removeClass(\"active\");\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <ul class=\"skipMenu\">\r\n");
      out.write("        <li><a href=\"#nav\">메인메뉴 바로가기</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <header class=\"clearFix\">\r\n");
      out.write("        <div class=\"headTop\">\r\n");
      out.write("            <a href=\"#void\"><i class=\"fas fa-bars\"></i></a>\r\n");
      out.write("            <div class=\"innerBox\">\r\n");
      out.write("                <h1 class=\"logo\">\r\n");
      out.write("                    <a href=\"index.html\">북새통문고</a>\r\n");
      out.write("                    <span>|</span>\r\n");
      out.write("                    <a href=\"index.html\">BOOK<span>Choice</span></a>\r\n");
      out.write("                </h1>\r\n");
      out.write("                <form action=\"#\">\r\n");
      out.write("                    <input class=\"text\" type=\"search\" autocomplete='on' placeholder=\"제목, 저자, 출판사 검색\" >\r\n");
      out.write("                    ");

                    	//로그인이 안되었을 경우에는 로그인, 회원가입 버튼을 보여준다.
                    	//로그인이 되었을 경우에는 로그아웃 버튼을 보여준다.
                    	if(session.getAttribute("sessionID")==null){//로그인x
                    
      out.write("\r\n");
      out.write("                    		<ul class=\"login\">\r\n");
      out.write("                    			<li><a href=\"SignUp-before.html\">회원가입</a></li>\r\n");
      out.write("                    			<li><a href=\"login.jsp\">로그인</a></li>                    			\r\n");
      out.write("                    		</ul>\r\n");
      out.write("                    ");

                    	}else{
                    
      out.write("\r\n");
      out.write("                    		<ul class=\"login\" style=\"position:absolute; top:0; right:-32px; color:yellow; font-size:16px;\">\r\n");
      out.write("                    			&nbsp;&nbsp;\r\n");
      out.write("                    			<li>\r\n");
      out.write("                    			");
      out.print(session.getAttribute("sessionID") );
      out.write("님이 로그인 되었습니다.\r\n");
      out.write("                    			</li>\r\n");
      out.write("                    			<li><a href=\"pro/logoutPro.jsp\"></a></li>\r\n");
      out.write("                    		</ul>\r\n");
      out.write("					");

                    	}
                    
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                </form>\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <ul id=\"nav\" class=\"clearFix\">\r\n");
      out.write("                        <li><a href=\"index.html\"><img src=\"icon/Home.svg\" alt=\"Home\">홈</a></li>\r\n");
      out.write("                        <li><a href=\"alaram.html\"><img src=\"icon/bell.svg\" alt=\"bell\">알림</a></li>\r\n");
      out.write("                        <li><a href=\"cart.html\"><img src=\"icon/Cart.svg\" alt=\"Cart\">카트</a></li>\r\n");
      out.write("                        <li><a href=\"myBookSatong.html\"><img src=\"icon/my.svg\" alt=\"my\">마이북새통</a></li>\r\n");
      out.write("                        <li><a href=\"location.html\"><img src=\"icon/location.svg\" alt=\"location\">찾아오시는 길</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <ul class=\"navIcon\">\r\n");
      out.write("                        <li><a href=\"alaram.html\"><img src=\"icon/bell.svg\" alt=\"bell\"></a></li>\r\n");
      out.write("                        <li><a href=\"cart.html\"><img src=\"icon/Cart.svg\" alt=\"Cart\"></a></li>\r\n");
      out.write("                        <li><a href=\"myBookSatong.html\"><img src=\"icon/my.svg\" alt=\"my\"></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"headBottom clearFix\">\r\n");
      out.write("            <div class=\"innerBox\">\r\n");
      out.write("                <ul class=\"headerMenu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"menu.html\">메뉴</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/download.svg\" alt=\"download\">\r\n");
      out.write("                                <a href=\"#void\">다운로드</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/Cart.svg\" alt=\"Cart\">\r\n");
      out.write("                                <a href=\"#void\">내 보관함</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/N_blue.svg\" alt=\"N_blue\">\r\n");
      out.write("                                <a href=\"#void\">신간</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/Best_Seller.svg\" alt=\"Best_Seller\">\r\n");
      out.write("                                <a href=\"#void\">베스트</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/naver.svg\" alt=\"naver\">\r\n");
      out.write("                                <a href=\"https://www.naver.com/\">네이버</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/kakao.svg\" alt=\"kakao\">\r\n");
      out.write("                                <a href=\"https://www.kakaocorp.com/page/\">카카오</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/google.svg\" alt=\"google\">\r\n");
      out.write("                                <a href=\"https://www.google.co.kr/\">구글</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <img src=\"icon/youtube.svg\" alt=\"youtube\">\r\n");
      out.write("                                <a href=\"https://www.youtube.com/\">유튜브</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"general.html\">일반</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"#void\">소설</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">경영/경제</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">인문/사회/역사</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">자기계발</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">에세이/시</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">여행</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">종교</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">외국어</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">과학</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"romance.html\">로맨스</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"#void\">현대물</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">역사/시대물</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">판타지물</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">할리퀸 소설</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"fantasy.html\">판타지</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"#void\">정통 판타지</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">퓨전 판타지</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">현대 판타지</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">게임 판타지</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"design.html\">디자인문구</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"#void\">디자이너/플래너/캘린터</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">노트/메모지</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">카드/편지/봉투</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">필기구/필통</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">앨범/레코트북/컨셉북</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">파일링/바인더</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">데스크/오피스</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">스티커</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">포장용품</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"life.html\">라이프</a>\r\n");
      out.write("                        <ul class=\"sub\">\r\n");
      out.write("                            <li><a href=\"#void\">키친</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">욕실</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">인테리어/데코</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">여행</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">개인소품</a></li>\r\n");
      out.write("                            <li><a href=\"#void\">계절상품</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"subBg\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
