/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.26
 * Generated at: 2022-11-21 09:16:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>TheBreadEarth &#124; 비건베이커리</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/icon_logo_shortcut.png\">\r\n");
      out.write("    <!-- Noto Sans -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans:wght@100;300;400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Noto Serif Korean  -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Serif+KR:wght@300;400;500;600;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <!-- Noto Sans Korean -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style_common.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\">\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"js/javascript.js\"></script>\r\n");
      out.write("     \r\n");
      out.write("    <script src=\"js/loading.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("	function checkValue(){\r\n");
      out.write("		if(!document.loginInfo.id.value){\r\n");
      out.write("			alert(\"아이디를 입력하세요\");\r\n");
      out.write("			document.loginInfo.id.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if(!document.loginInfo.password.value){\r\n");
      out.write("			alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("			document.loginInfo.password.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<header>\r\n");
      out.write("    <div class=\"subBg\"></div>\r\n");
      out.write("    <div class=\"innerBox\">\r\n");
      out.write("        <h1 class=\"logo\"><a href=\"index.html\"><img src=\"images/logo.png\" alt=\"TheBreadEarth logo\"></a></h1>\r\n");
      out.write("        <ul class=\"rightGnb\">\r\n");
      out.write("            <li><a href=\"login.html\">로그인</a></li>\r\n");
      out.write("            <li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("            <li><a href=\"#\">주문조회</a></li>\r\n");
      out.write("            <li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <form class=\"leftGnb\">\r\n");
      out.write("            <input type=\"search\">\r\n");
      out.write("            <a href=\"#\"><img src=\"images/icon_serch.png\" alt=\"돋보기 아이콘\"></a>\r\n");
      out.write("        </form>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <div class=\"mobileNav\">\r\n");
      out.write("                <div class=\"navLogo\"><a href=\"#\"><img src=\"images/logo.png\" alt=\"TheBreadEarth logo\"></a></div>\r\n");
      out.write("                <div class=\"xBtn\"><a href=\"#\"><img src=\"images/cancel.svg\" alt=\"cancel button\"></a></div>\r\n");
      out.write("                <div class=\"mloginBtn\"><a href=\"login.html\"><img src=\"images/loginBtn.svg\" alt=\"\"></a></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul id=\"nav\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"brand_story.html\">브랜드 스토리</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"#\">브랜드소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">연혁</a></li>\r\n");
      out.write("                        <li><a href=\"#\">매장소개</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"product_list.html\">MENU</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"#\">전체메뉴</a></li>\r\n");
      out.write("                        <li><a href=\"#\">베스트메뉴</a></li>\r\n");
      out.write("                        <li><a href=\"#\">베이커리</a></li>\r\n");
      out.write("                        <li><a href=\"#\">디저트</a></li>\r\n");
      out.write("                        <li><a href=\"#\">케이크</a></li>\r\n");
      out.write("                        <li><a href=\"#\">쿠키</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"product_md_list.html\">이벤트 상품</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"#\">특가상품</a></li>\r\n");
      out.write("                        <li><a href=\"product_md_list.html\">MD상품</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">리뷰</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"#\">베스트 리뷰</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">공지사항</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">고객센터</a>\r\n");
      out.write("                    <ul class=\"sub\">\r\n");
      out.write("                        <li><a href=\"#\">온라인상담</a></li>\r\n");
      out.write("                        <li><a href=\"#\">제품문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">QnA</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"mobileNavBanner\">\r\n");
      out.write("                    <a href=\"#\"><img src=\"images/mobile_banner.jpg\" alt=\"모바일광고 배너\"></a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"hamBtn\"><a href=\"#\"><img src=\"images/hamBtn.svg\" alt=\"ham button\"></a></div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- #mainBanner -->\r\n");
      out.write("<!-- container -->\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("    <div class=\"loginWrap\">\r\n");
      out.write("        <h2 class=\"loginTitle\">LOGIN</h2>\r\n");
      out.write("        <form id=\"loginForm\"  action=\"pro/loginPro.jsp\" method=\"post\" name=\"loginInfo\" onsubmit=\"return checkValue();\">\r\n");
      out.write("            <div class=\"idBox\">\r\n");
      out.write("                <label for=\"userName\"></label>\r\n");
      out.write("                <input id=\"userName\" type=\"text\" name=\"id\" placeholder=\" ID를 입력해주세요\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"pwBox\">\r\n");
      out.write("                <label for=\"password\"></label>\r\n");
      out.write("                <input id=\"password\" type=\"password\" name=\"password\" placeholder=\" PW를 입력해주세요\">\r\n");
      out.write("            </div>            \r\n");
      out.write("            <ul>              \r\n");
      out.write("                <li class=\"saveId\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"images/icon_checkbox.png\" alt=\"checkbox\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <p>아이디저장</p>                    \r\n");
      out.write("                </li>  \r\n");
      out.write("                <li><a href=\"#\">아이디찾기 / </a></li>\r\n");
      out.write("                <li><a href=\"#\">비밀번호찾기</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <input class=\"loginBtn\" type=\"submit\" value=\"로그인\"/>\r\n");
      out.write("            \r\n");
      out.write("              <div class=\"snsLogin\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\" class=\"btnNaver\" onclick=\"\">\r\n");
      out.write("                            <span>네이버 로그인</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\" class=\"btnGoogle\" onclick=\"\">\r\n");
      out.write("                            <span>구글 로그인</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#none\" class=\"btnKakao\" onclick=\"\">\r\n");
      out.write("                            <span>카카오계정 로그인</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"signLink\">\r\n");
      out.write("                아직 회원이 아니신가요?<br>\r\n");
      out.write("                고객님을 위한 다양한 혜택이 준비되어 있습니다.<br>\r\n");
      out.write("                <a href=\"#\" class=\"signBtn\">회원가입</a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </form>\r\n");
      out.write("           ");

             	String msg = request.getParameter("msg");
             	if(msg!=null && msg.equals("0")){
             		out.println("<script>alert('비밀번호가 맞지 않습니다.')</script>");
             	}else if(msg!=null && msg.equals("-1")){
             		out.println("<script>alert('아이디가 존재하지 않습니다.')</script>");
             	}
           
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"footTop\">\r\n");
      out.write("        <div class=\"innerBox\">\r\n");
      out.write("            <ul class=\"util\">\r\n");
      out.write("                <li><a href=\"#\"><strong>개인정보처리방침</strong></a></li>\r\n");
      out.write("                <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                <li><a href=\"#\">이용안내</a></li>\r\n");
      out.write("                <li><a href=\"#\">이메일무단수집거부</a></li>\r\n");
      out.write("                <li><a href=\"#\">법적고지</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"arrowUp\">\r\n");
      out.write("            <a href=\"#\"><img src=\"images/scroll_arrow_up.png\" alt=\"scroll-up\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"innerBox\">\r\n");
      out.write("        <h1 class=\"footLogo\"><a href=\"#\"><img src=\"images/foot_logo.png\" alt=\"foot logo\"></a></h1>\r\n");
      out.write("        <div class=\"footMiddle\">\r\n");
      out.write("            <div class=\"addressWrap\">\r\n");
      out.write("                <address>\r\n");
      out.write("                    <p><strong>사업자명 : </strong><span>(주)더브레드얼쓰</span><strong>대표이사 : </strong><span>김OO</span></p>\r\n");
      out.write("                    <p><strong>사업자등록번호 : </strong><span>000-00-00000</span><strong>주소 : </strong><span>서울특별시 00구 00동\r\n");
      out.write("                            00로 00 00타워 A동</span></p>\r\n");
      out.write("                    <p><strong>메일 : </strong><span>TheBreadEarth@naver.com</span></p>\r\n");
      out.write("                </address>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"snsMobile\">\r\n");
      out.write("                <ul class=\"snsInfo\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div><img src=\"images/icon_sns_facebook.png\" alt=\"페이스북\"></div>\r\n");
      out.write("                            <span>페이스북</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div><img src=\"images/icon_sns_youtube.png\" alt=\"유튜브\"></div>\r\n");
      out.write("                            <span>유튜브</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <div><img src=\"images/icon_sns_insta.png\" alt=\"인스타\"></div>\r\n");
      out.write("                            <span>인스타그램</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"copy\">copyrightⓒ 2022 All rights reserved by Kim Jung Hyun</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
